---
- hosts: windows
  gather_facts: false
  become: yes

  tasks:
  - name: Include variables
    include_vars: my_ad_vars.yml

  - name: Call win_ad_install Role
    include_role:
      name: win_ad_install
